import os
import json
import requests

# --- CONFIGURATION ---
# The API Key is retrieved from GitHub Secrets (Environment Variable)
API_KEY = os.environ.get("YOUTUBE_API_KEY")
if not API_KEY:
    raise Exception("Error: YOUTUBE_API_KEY is missing from environment variables.")

# Search parameters
SEARCH_QUERY = "NBA highlights full game"
REGION_CODE = "IL" # Filter for videos allowed in Israel
MAX_RESULTS = 15

# YouTube API URL
url = f"https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&q={SEARCH_QUERY}&regionCode={REGION_CODE}&relevanceLanguage=en&maxResults={MAX_RESULTS}&order=date&key={API_KEY}"

def main():
    print(f"Fetching videos for region: {REGION_CODE}...")
    
    try:
        response = requests.get(url)
        response.raise_for_status() # Raise error for bad status codes
        data = response.json()

        if "items" not in data:
            print("No items found in response.")
            return

        # Extract only the Video IDs
        video_ids = [item["id"]["videoId"] for item in data["items"]]
        print(f"Successfully found {len(video_ids)} videos: {video_ids}")

        # Construct the playlist data structure
        output_data = {
            "1": video_ids,                             # Channel 1: Dynamic NBA
            "2": ["dQw4w9WgXcQ", "L_jWHffIx5E"],        # Channel 2: Static Backup/Comedy
            "last_updated": "Auto-generated by GitHub Actions"
        }

        # Save to the root directory so index.html can read it
        with open("playlist.json", "w") as f:
            json.dump(output_data, f, indent=2)
            
        print("playlist.json saved successfully.")

    except Exception as e:
        print(f"An error occurred: {e}")
        exit(1)

if __name__ == "__main__":
    main()
